# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # specify the version you desire here
      - image: circleci/node:8
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/app/dist

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Yarn install(Functions)
          # command: cd functions && yarn add firebase-functions@latest firebase-admin@latest --save  && yarn install && cd ../
          command: cd functions && yarn add firebase-functions@latest firebase-admin@latest --save  && yarn install

      - run:
          name: Add .env(Functions)
          command: |
            echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" > .env
            echo "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> .env
            echo "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL" >> .env
            echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
            echo "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> .env
            echo "FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> .env

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Yarn clean
          command: cd ../ && yarn clean

      - run:
          name: Firebase add
          command: yarn add firebase-tools@latest -D

      - run:
          name: Yarn install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Yarn build
          command: yarn build

      # - run: 
      #     name: Firebase config set
      #     command: node_modules/.bin/firebase functions:config:set environment.apikey="AIzaSyAcwRZg-BkmnhjN6vCjE3BUppk4CvbqiiI" && node_modules/.bin/firebase functions:config:set environment.authdomain="oi-machi-saga.firebaseapp.com" && node_modules/.bin/firebase functions:config:set environment.databaseurl="https://oi-machi-saga.firebaseio.com" && node_modules/.bin/firebase functions:config:set environment.projectid="oi-machi-saga" && node_modules/.bin/firebase functions:config:set environment.storagebucket="" && node_modules/.bin/firebase functions:config:set environment.messagingsenderid="956235970515"

      - run:
          name: Firebase deploy
          # command: node_modules/.bin/firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"
          command: node_modules/.bin/firebase deploy --project "$FB_PROJECTID" --token "$FIREBASE_TOKEN"

      - persist_to_workspace:
            root: .
            paths:
                - .        
      # run tests!
      # - run: yarn test